//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.AccountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceReference.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Register", ReplyAction="http://tempuri.org/IAccountService/RegisterResponse")]
        WebClient.AccountServiceReference.User Register(WebClient.AccountServiceReference.User request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Register", ReplyAction="http://tempuri.org/IAccountService/RegisterResponse")]
        System.Threading.Tasks.Task<WebClient.AccountServiceReference.User> RegisterAsync(WebClient.AccountServiceReference.User request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Login", ReplyAction="http://tempuri.org/IAccountService/LoginResponse")]
        WebClient.AccountServiceReference.User Login(WebClient.AccountServiceReference.User request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Login", ReplyAction="http://tempuri.org/IAccountService/LoginResponse")]
        System.Threading.Tasks.Task<WebClient.AccountServiceReference.User> LoginAsync(WebClient.AccountServiceReference.User request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PhoneNumber;
        
        public User() {
        }
        
        public User(int UserId, string Email, string Name, string Password, string PhoneNumber) {
            this.UserId = UserId;
            this.Email = Email;
            this.Name = Name;
            this.Password = Password;
            this.PhoneNumber = PhoneNumber;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : WebClient.AccountServiceReference.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<WebClient.AccountServiceReference.IAccountService>, WebClient.AccountServiceReference.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.AccountServiceReference.User WebClient.AccountServiceReference.IAccountService.Register(WebClient.AccountServiceReference.User request) {
            return base.Channel.Register(request);
        }
        
        public void Register(ref int UserId, ref string Email, ref string Name, ref string Password, ref string PhoneNumber) {
            WebClient.AccountServiceReference.User inValue = new WebClient.AccountServiceReference.User();
            inValue.UserId = UserId;
            inValue.Email = Email;
            inValue.Name = Name;
            inValue.Password = Password;
            inValue.PhoneNumber = PhoneNumber;
            WebClient.AccountServiceReference.User retVal = ((WebClient.AccountServiceReference.IAccountService)(this)).Register(inValue);
            UserId = retVal.UserId;
            Email = retVal.Email;
            Name = retVal.Name;
            Password = retVal.Password;
            PhoneNumber = retVal.PhoneNumber;
        }
        
        public System.Threading.Tasks.Task<WebClient.AccountServiceReference.User> RegisterAsync(WebClient.AccountServiceReference.User request) {
            return base.Channel.RegisterAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.AccountServiceReference.User WebClient.AccountServiceReference.IAccountService.Login(WebClient.AccountServiceReference.User request) {
            return base.Channel.Login(request);
        }
        
        public void Login(ref int UserId, ref string Email, ref string Name, ref string Password, ref string PhoneNumber) {
            WebClient.AccountServiceReference.User inValue = new WebClient.AccountServiceReference.User();
            inValue.UserId = UserId;
            inValue.Email = Email;
            inValue.Name = Name;
            inValue.Password = Password;
            inValue.PhoneNumber = PhoneNumber;
            WebClient.AccountServiceReference.User retVal = ((WebClient.AccountServiceReference.IAccountService)(this)).Login(inValue);
            UserId = retVal.UserId;
            Email = retVal.Email;
            Name = retVal.Name;
            Password = retVal.Password;
            PhoneNumber = retVal.PhoneNumber;
        }
        
        public System.Threading.Tasks.Task<WebClient.AccountServiceReference.User> LoginAsync(WebClient.AccountServiceReference.User request) {
            return base.Channel.LoginAsync(request);
        }
    }
}
